### ISSUE TITLE
after update to 18.1.5.1 Missing Reference Mono.Posix 

### ISSUE THREAD

**Issue by larspl** [eXpandFramework/eXpand#135]
Hi Tolis, after update 18.1.5.1 the csScript.CS nget needs updated, recompile was ok, without a error. after deployment on test server the worldcreator stops with missing DLL / reference Mono.Posix 

Its a bit strange that mono and in this case Posix is missing. 
Please look at the csScript requirements to avoid all un-needed nuget libs. 

Cheers Lars

**Comment by oleg-shilo** [comment]
Hi there,
Indeed cs-script has dependancy on _Mono.Posix.dll_. It is required for implementing custom system wide `Mutex` which is otherwise not available on Mono-Linux. 

The cs-script codebase contains _Mono.Posix.dll_ which is only a facade assembly. Thus the assembly can be built on Windows. The code that actually invokes _Mono.Posix.dll_ at runtime is not executed on Windows even if it is running on Mono. But on Linux _Mono.Posix.dll_ is automatically loaded from GAC.

I hope it helps.

**Comment by larspl** [comment]
Hi Oleg, 

that the cs-script is referencing the Mono.Posix its clear now. 
But why need the WorldCreator load that ? 
The error occurred:
    Type:       InvalidOperationException
    Message:    Exception occurs while initializing the &#39;Xpand.ExpressApp.WorldCreator.WorldCreatorModule&#39; module: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

here is the error Stack:
at DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
 at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
 at DevExpress.ExpressApp.XafApplication.Setup(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
 at DevExpress.ExpressApp.XafApplication.Setup()
 at x.x.x.Web.Global.Session_Start(Object sender, EventArgs e) in c:\tfsagents\agent1\_work\26\s\x.x.x.Web\Global.asax.cs:line 112
 at System.Web.SessionState.SessionStateModule.CompleteAcquireState()
 at System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
 at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
 at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
 at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)
---  ------  ---
    InnerException:

            Type:       ReflectionTypeLoadException
            Message:    Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
            Data:       0 entries
            LoaderExceptions:       1 entries
                    &#39;0&#39;        &#39;Could not load file or assembly &#39;Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756&#39; or one of its dependencies. The system cannot find the file specified.&#39;Stack trace: 

 at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
 at System.Reflection.Assembly.GetTypes()
   at System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__17`2.MoveNext()
 at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
 at Xpand.ExpressApp.WorldCreator.WorldCreatorModule.RegisterDerivedTypes() in C:\expandframework\eXpand\Xpand\Xpand.ExpressApp.Modules\WorldCreator\Module.cs:line 163
 at Xpand.ExpressApp.WorldCreator.WorldCreatorModule.Setup(ApplicationModulesManager moduleManager) in C:\expandframework\eXpand\Xpand\Xpand.ExpressApp.Modules\WorldCreator\Module.cs:line 133
 at DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
            InnerException is null

i assume that his additional loading of - my point of view - unnecessarily objects and classes  slow down the app 

Regards Lars

**Comment by apobekiaris** [comment]
I published nugets for v18.1.5.3 they should fix this problem. 

I haven't managed to load the POSIX assembly on my side. However it looks like assembly.GetTypes used in RegisterDeriveTypes and in a few other places needs to be replaced with Mono calls that will not load into the domain.

**Comment by oleg-shilo** [comment]
Bingo!

The type CS-Script type `Mono.Unix.FileMutex` references _Mono.Posix.dll_. But this type is never touched (loaded) at runtime on Windows: 

```C#
internal class LinuxSystemWideLock : ISystemWideLock, IDisposable
{
    Mono.Unix.FileMutex mutex;
. . . 
public SystemWideLock(string file, string context)
{
    bool isLinux = (Environment.OSVersion.Platform == PlatformID.Unix);

    if (isLinux)
    {
        mutex = new LinuxSystemWideLock(file, context);
    }
    else
    . . .
```
But when you call <cs-script assembly>.GetTypes() you effectively is trying to load the type. In a way it is not so uncommon. I remember experiencing very similar problem with one of the major dotnet.core assemblies, which contained types that were not loadable at runtime. I just needed to handle the exception in my case.

**Comment by apobekiaris** [comment]
@oleg-shilo thnks a lot for the details. Such generic calls are not ideal when done from reflection.

@larspl I modified the source code and test it and lazy loading seems to work fine. The Cs-script dll gets loaded only when the ExpressionEvaluator is used. As I said before I never got POSIX to load on my side so I cannot test properly. However @oleg-shilo statements are true and since the framework does not call `GetTypes` anymore there is no need for the package and I removed it as well. @larspl I can share the nuget packages for that build if you wish to test before next release.

**Comment by expand** [comment]
@vimarx System.Core apparently is a .NET system dll and is needed. why it is looking for v2.0.5 I am not certain, however all well since windows updates addressed your problem.

From your stack it looks that you found another place that it might relate to loading problems due to reflection calls. So I have replace reflection again with Mono calls from this [patch](https://www.dropbox.com/s/eeojbmmuw94avtn/eXpandFramework-18.1.5.34.exe?dl=0)

**Comment by apobekiaris** [comment]
in 18.1.5.4 i re-implemented a compile on the fly approach with no dependencies. Let me know if I miss anything but there shouldn't be any cost unless you actually use the [EvaluateExpressionOperator](https://github.com/expand/eXpand/blob/626117d23a03e078369901c6482ac3e0ce71c955/Xpand/Xpand.Persistent/Xpand.Persistent.Base/General/CustomFunctions/EvaluateExpressionOperator.cs)

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
