### ISSUE TITLE
FriendlyURL

### ISSUE THREAD

**Issue by emeyke** [eXpandFramework/eXpand#154]
Anyone using FriendlyUrl option?
Or successfully implemented own design?
DX suggests this:
https://www.devexpress.com/Support/Center/Question/Details/S132933/how-to-provide-short-and-user-friendly-urls-for-xaf-web-views
Tolis, your opinion?

Cheers,
Ev

**Comment by apobekiaris** [comment]
https://www.devexpress.com/Support/Center/Question/Details/T406218/how-to-change-the-default-url-format-in-xaf-web-apps has a vb sample

I remember we had a similar implementation in the past which was removed due to breaking changes. I need research time but it looks that cannot be supported everywhere just the first page of the listview probably.

**Comment by apobekiaris** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
