### ISSUE TITLE
threadSafeLayer

### ISSUE THREAD

**Issue by melihyilman** [eXpandFramework/eXpand#318]
Hi @apobekiaris 

It doesn't looks fixed at https://github.com/eXpandFramework/eXpand/issues/308

On demo project it works well, but existing project after I clicked login button on web application i got this.

Exception thrown: 'DevExpress.Xpo.Exceptions.AssociationInvalidException' in DevExpress.Xpo.v18.2.dll
The association attribute cannot be used for member 'Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentTypeInfo.TypeAttributes' because class 'Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentAttributeInfos.PersistentAttributeInfo' is not persistent.

what does it mean? If I set threadSafe both objectspaces then I got this.

**Comment by apobekiaris** [comment]
>Exception thrown: 'DevExpress.Xpo.Exceptions.AssociationInvalidException' in DevExpress.Xpo.v18.2.dll
The association attribute cannot be used for member 'Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentTypeInfo.TypeAttributes' because class 'Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentAttributeInfos.PersistentAttributeInfo' is not persistent.

it can just be a side effect of the situation you are in or you just miss configure something. Really without being able to repro I cannot guess especially with those short messages you posting. Try to add classes and modules from your main solution in the Demo that works well until you understand where is the problem. Post details and happy to help you solve it.

**Comment by skybluex3** [comment]
Hi again @apobekiaris 
I think i found something. Is it neccesary ? in worldcreator.module line 135 func: CustomizeTypeInfo

```
public override void CustomizeTypesInfo(ITypesInfo typesInfo)
        {

            base.CustomizeTypesInfo(typesInfo);
            AddToAdditionalExportedTypes(BaseImplNameSpace);
            if (RuntimeMode)
            {
                var classInfos = XpoTypesInfoHelper.GetXpoTypeInfoSource().XPDictionary.Classes.OfType<XPClassInfo>().Where(info => info.IsPersistent &&
                                                                                                                                    WorldCreatorTypeInfoSource.Instance.RegisteredEntities.Contains(info.ClassType));
                foreach (var xpClassInfo in classInfos)
                {
                    xpClassInfo.AddAttribute(new NonPersistentAttribute()); // i think i got exception bcz of this
                }
                ExistentTypesMemberCreator.CreateMembers(this);
            }
        }

```

xpClassInfo: Full name is Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentAttributeInfos.PersistentAttributeInfo

**Comment by apobekiaris** [comment]
that line is the start of your exception stack perhaps however the reason is stated from the exception message

>The association attribute cannot be used for member 'Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentTypeInfo.TypeAttributes' because class 'Xpand.Persistent.BaseImpl.PersistentMetaData.PersistentAttributeInfos.PersistentAttributeInfo' is not persistent.

Can you try on an empty db? do u have the same problem? if not you need to selectively disable your PersistentAssemblyInfo until you find the problem. Set the `DoNotCompile` from the UI for all your assemblies

**Comment by skybluex3** [comment]
I'll check tomorrow.thanks
