### ISSUE TITLE
Xpand.XAF.Modules.ModelViewInheritance.dll ClickOnce Issue

### ISSUE THREAD

**Issue by capricciobob** [eXpandFramework/eXpand#339]
I am doing a ClickOnce deployment and it has always been fine. With this latest release, it is requiring me to include the Xpand.XAF.Modules.ModelViewInheritance.dll and everytime my customer tries to install they get this error. Is there anything different about how this dll is signed? Anything else that would make this dll troublesome? Thanks!

Xpand.XAF.Modules.ModelViewInheritance.dll, has a different computed hash than specified in manifest.

**Comment by apobekiaris** [comment]
hmm it is not clear where is there problem with click once. I did not have failing reports for this approach until now.

The `ModelInheritance` follows a special versioning, is patched on the first build to match the the DevExpress version. You can read details at 
https://github.com/eXpandFramework/XAF/tree/master/tools/Xpand.VersionConverter

Having this information can you post details on how to repro the issue?

**Comment by capricciobob** [comment]
It looks like the DLL gets updated every time I build and publish. The file DateModified changes every time. I think this is causing ClickOnce to not have the correct hash on the file. When you launch the application, ClickOnce thinks the file has been corrupted. I went ahead and removed the NuGet reference and took a copy of the dll and referenced it directly from my project and the file is no longer changing every time. ClickOnce works now. It is a workaround for now, thanks.

**Comment by apobekiaris** [comment]
I am not sure we ClickOnce this is corrupted. 

What happens in details is: 
when you build a project having this nuget on `AfterBuild` target this scripts executes.
https://github.com/eXpandFramework/XAF/blob/a7aa57799e80aa835e9d39d4c1dc221740818fe0/tools/Xpand.VersionConverter/Xpand.VersionConverter.ps

if you read through it you will notice that this is done once.
https://github.com/eXpandFramework/XAF/blob/a7aa57799e80aa835e9d39d4c1dc221740818fe0/tools/Xpand.VersionConverter/Xpand.VersionConverter.ps1#L59

You cannot use the assembly without **one at least build** 

The assembly that will be patched is the one in the nuget `Packages` folder and not in your bin, so be careful if you share this folder with projects that use different DX version. It also means that will not patched again if you do a clean build.

Let me know if you still facing problems please, my intention to transition a big part of the framework like this Nuget  because they minimize the support cost.
