### ISSUE TITLE
ImportWizard

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#424]
Hi Tolis,

I think the Importwizard has a fix Reference to a specific Version. The Version installed is 2.9.1 (DocumentFormat.OpenXml).

If I go back to 2.7.2 everything works.

iXISXRM.Win.exe Error: 0 : 31.05.19 16:09:02.544	================================================================================
The error occurred:

	Type:       FileLoadException
	Message:    Die Datei oder Assembly "DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
	Data:       0 entries
	Stack trace:

   bei Xpand.ExpressApp.ImportWizard.Win.Wizard.ExcelImportWizard.CloseExcelDocumentNoThrow()
   bei Xpand.ExpressApp.ImportWizard.Win.Wizard.ExcelImportWizard.ExcelImportWizard_FormClosing(Object sender, FormClosingEventArgs e) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ImportWizard.Win\Wizard\ExcelImportWizard.cs:Zeile 112.
   bei System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   bei System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
	InnerException is null

**Comment by apobekiaris** [comment]
Hi CWolffIF,

I do not follow you ImportWizard uses 2.7.2

https://github.com/eXpandFramework/eXpand/blob/6deb9088ff3ea570123234ac7e18fe462d9fcbf6/Xpand/Xpand.ExpressApp.Modules/ImportWizard.Win/packages.config#L3

**Comment by CWolffIF** [comment]
Hi Tolis,
yes that´s correct. But if you don´t have Version 2.7.2 but a higher Version 2.9.1 on the client system it doesn´t work anymore.
On my client system Version 2.9.1 is installed and the error appears. if I downgrade to 2.7.2 it works.

**Comment by apobekiaris** [comment]
I understand the situation however there is not much eXpandFramework can do about it. What I mean is that each module may use a number of packages that differ from the ones you have in your system (this part is not so clear to me, assemblies shoudl be in your bin to avoid conflicts, how the system is involved). So to continue, eXpandFramework cannot take action each time there is a conflict with a user system and is up to user to resolve the assembly loading problem. The process of how the runtime loads assemblies is documented at https://docs.microsoft.com/en-us/dotnet/framework/deployment/how-the-runtime-locates-assemblies where the most common way is to use AssemblyBinding in your app.config. 

In addition this is a FileLoadException, you can examine the FusionLog property and you can see all the paths that were probed for locating the assembly. Adding the correct version there it will resolve the problem. Moreover one can apply manual loading techincs e.g. before anything is loaded do Assembly.LoadFromFile(pathToTheVCorrectverion), this will load the correct assembly into the Domain and the problem will be resolved.

let me know if my suggestions help u, or if you have an different opinion

**Comment by CWolffIF** [comment]
You are right, that there could be more versions of a special module on a system. But normally (the most nuget packages) say, that you need a version or greater, f.e. >= 2.7.2. The downward compatibility should be the aim. If you a big project you use many modules in the project. An if each module use the same package / *.dll with different Version without downgrade compatibility you have
V 1.0, V1.1, V1.2, V1.3, V1.4, etc. on the System with all the problems of fixed errors.
Cause the ImportWizard is a eXpand Module I do not understand why it needs Version 2.7.2 or is the DocumentFormat.OpenXml Version 2.9.1 not downward compatible.

**Comment by apobekiaris** [comment]
>on the System with all the problems of fixed errors.
Cause the ImportWizard is a eXpand Module I do not understand why it needs Version 2.7.2 

the reason is simple the module works, upgrading will change its state and most probably it will create more problems. I do not have tests for this module, in fact I did not even author it, it was contributed from another user.

There are many packages that maybe there is a newer version. If there is a reason e.g. we need the new feature offered by the package yes sure I agree the risk is justifiable.

The alternative if you want to use the latest version is to install it on your project, this will create the binding redirects automatically, meaning that your system with all its modules will use the latest assembly version **as 2 versions of the same assembly cannot coexist** the loading will take place as the doc I posted before.

This is a really simple solution why it does not fit your needs? it will answer to your question `or is the DocumentFormat.OpenXml Version 2.9.1 not downward compatible.` Having that as a start I can consider spending valuable resources.

eXpandFramework already applies that for other packages e.g. the System.Reactive has a dependency to an old version of System.ValueTuple while other modules use the latest, similar for NewTon.Json dependencies. 

**Should I upgrade all packages to the latest? how many problems this will create and for what reason?** there is a solution for this and latest version does not mean better and many times does not mean compatible and to deal with the compatibility problems you will create you need resources and maybe you can break other user projects and so on.

I hope you understand my position here. Please try my suggestions and let me know if you have additional feedback.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
