### ISSUE TITLE
Packaging and deployment tool for XAF winform APP

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#510]
Hi,

I would like to deploy a winform app but i had really bad experience with ClickOnce. 
After looking a bit I discovered Squirrel which is very simple but apparently the project is not being maintained anymore. 

Do you have a suggestion on what i could use for the winform to package and manage the updates for the XAF app ? Windows bridge is not a option as i have customers with Windows 7. 

You expertise would be welcome :-)

BR
ISA

**Comment by isatahiri** [comment]
Moreover i cannot use the Xaf updater as i do not user moduleinfo :-(

**Comment by apobekiaris** [comment]
I do not have deployment exeperience, however I know that XAF users use clickonce with success. The clickonce technology however takes too much initiatives and hides stuff in order to automate the deployment. It really depends on your scenario, however a zip with all assemblies it should work the same

**Comment by isatahiri** [comment]
Thanks Tolis. 

Just for info there are some interesting suggestions from Dennis in this ticket : 
https://www.devexpress.com/Support/Center/Question/Details/T806232/packaging-and-deployment-tool-for-xaf-winform-app
