### ISSUE TITLE
XpandSystemAspNetModule : Listview column missing node in editor

### ISSUE THREAD

**Issue by Ezeckiel2517** [eXpandFramework/eXpand#525]
I just compare a web model that use XpandSystemAspNetModule from version 19.1.402 with version 19.1.503 and notice some nodes for listview column are missing (or no longer supported??).

See picture
![image](https://user-images.githubusercontent.com/15835320/63964574-66fee800-ca65-11e9-8360-16e71436e94e.png)

Is this a bug or something we need to configure?

I specially used the OptionsColumnGridView\Settings attributes and when running my app, those settings are no longer apply by the module.

**Comment by apobekiaris** [comment]
probably a conflict with #516

**Comment by Ezeckiel2517** [comment]
Is it possible the modelmapper map the option on class GridViewColumn ?
![image](https://user-images.githubusercontent.com/15835320/63966908-4f762e00-ca6a-11e9-8fa9-0294377fe846.png)

Because the missing attributes comes from class GridViewDataColumn. Maybe it simply miss a mapping?

**Comment by Ezeckiel2517** [comment]
BTW the visibility on the property is "Content", so not related to #516 

```csharp
[Category("Behavior"), PersistenceMode(PersistenceMode.InnerProperty), DesignerSerializationVisibility(DesignerSerializationVisibility.Content), NotifyParentProperty(true)]
public GridViewDataColumnSettings Settings 
{
	get { return (GridViewDataColumnSettings)ColumnAdapter.Settings; } 
}
```

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ModelMapper: Map GridViewDataColumn instead of GridViewColumn #525](https://github.com/eXpandFramework/DevExpress.XAF/commit/91913df8c0b7084fb446cc824f5ed64ebc8b211f)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by Ezeckiel2517** [comment]
Any idea when the package 19.1.603.0 will be available to test?
I just test it with 19.1.602.6 and it is still not fixed.

**Comment by apobekiaris** [comment]
Some clarification, the bot notifies about the DevExpress.XAF repo meaning that is available at the lab servers and will be available on the next minor of this repro. You can however install the package from the lab servers into your module and this should work. Also you most problably need to configure your binding but the next switches can help (in your csproj)
```xml
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
```

**Comment by Ezeckiel2517** [comment]
I have update ModelMapper to version 1.1.39.2 on nightly and using reflector, the PredefinedMap.cs still have to old map on GridViewColumn. I should be GridViewDataColumn when I looked at the changeset.

Something broken with the package?

**Comment by apobekiaris** [comment]
I am not sure what happened it looks like the ModelMapper version was not bumped from the CI. Bumping it manually and let's keep an eye to it.

**Comment by apobekiaris** [comment]
However still not intergrated with eXpand packages so it won't work unless u modify the eXpand sources manually and rebuild them

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [ModelMapper: Map GridViewDataColumn instead of GridViewColumn #525](https://github.com/eXpandFramework/DevExpress.XAF/commit/2f63cf144d8f3be481931037eef3a20664c94f85)
* [Bump ModelMapper #525](https://github.com/eXpandFramework/DevExpress.XAF/commit/bdbb70f268399729aefbc734fbe74c0eb54a3e61)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [lab-Pipeline uses wrong artifacts #525 #545](https://github.com/eXpandFramework/DevExpress.XAF/commit/dcef4205f25e366f55a6f0bee4cad00daab3eaa6)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment]
eXpand.lab release [19.1.602.7](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.7) includes commit that relate to this task:

* [Bump standalone packages #471 #525](https://github.com/eXpandFramework/eXpand.lab/commit/f1f96e911b6fea8a1b2e91641b7b0726614410d3)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by Ezeckiel2517** [comment]
This issue is now fixed.
