### ISSUE TITLE
Xpand Registration and Anonymous Login in one Application

### ISSUE THREAD

**Issue by ThomasVetterling** [eXpandFramework/eXpand#578]
If I enable both
'Registration' and 'AnonymousAuthentication' 
im not able to register new users anymore.

That's surely because the Login-Form is never to be shown as with 'AnonymousAuthentication'
the "Anonymous"-User is allways allready logged in. 

Even when I press on LogOff-Action the Loginform is not shown anymore

**Expected behavior**
How both of the  Options can be switched on and both will be work?
(Probably i could put a 'LOGOFF'-Action in my template and LogOff from Application. )

Any hint would be nice.

**Comment by apobekiaris** [comment]
this is what it worked for me
1. New Xpand Solution from VS project solution with Xpand security install
2. Run the app and add an AnonymousLogin permission to USer role
3. Configure the model
```xml
<Options>
    <Athentication>
      <AnonymousAuthentication Enabled="True" AnonymousUser="User" />
    </Athentication>
    <Registration Enabled="True" RoleModelClass="Xpand.Persistent.BaseImpl.Security.XpandPermissionPolicyRole" UserModelClass="Xpand.Persistent.BaseImpl.Security.XpandPermissionPolicyUser" />
  </Options>
```

Now you should see Login instead of LogOff and when Login u should be redirected to the login page with registration enable. You most probably need to configure your User role further

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
