### ISSUE TITLE
Nullreference in CloneModelView module

### ISSUE THREAD

**Issue by jacobdeboer33** [eXpandFramework/eXpand#611]
Hi Tolis

I'm getting a nullreference when starting an application that uses the clonemodelview module. Here is the relevant stacktrace:

De objectverwijzing is niet op een exemplaar van een object ingesteld. (nullreference exception)

   bij Xpand.XAF.Modules.CloneModelView.ModelViewClonerUpdater.UpdateNode(ModelNode node) in D:\a\1\s\src\Modules\CloneModelView\ModelViewClonerUpdater.cs:regel 17

Thanks,
Jacob

**Comment by expand** [comment]
eXpand.lab release [19.2.300.16](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.300.16) includes commit that relate to this task:

* [Bump standalone packages
 1. CloneModelView: Create new views instead of Cloning #601 #611](https://github.com/eXpandFramework/eXpand.lab/commit/7f1ebaf5943cea3e0a0907e60c38abd391f88154)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
