### ISSUE TITLE
Alternative way / path for creation of ModelMapperAssemblyWin.dll 

### ISSUE THREAD

**Issue by neuropseudolonicher** [eXpandFramework/eXpand#725]
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
We have a Windows application that is made available to the users via Citrix sessions provided via a loadbalanced Citrix environment.
The situation occurs that sometimes a host is serving more than one Citrix session, in this case the application fails to startup as the sessions are blocking each other because the creation of *ModelAssembly.dll and ModelMapperAssemblyWin.dll in application directory is actually only possible once.
We found a way to bypass this for the library being created by Devexpress itself based on information provided in https://supportcenter.devexpress.com/ticket/details/q351193/disable-generating-modelassembly-dll-for-winapp, but the library created by eXpand is still being created in the application folder.
Is there a possibilty to create ModelMapperAssemblyWin.dll in RAM, too?

𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
02. ❤ Bronze Sponsor
03. ❤ Sponsor
04. ❤ Backer
05. Installation
06. ShowStopper
07. Nuget
08. Contribution
09. BreakingChange
10. ReproSample
11. Deployment
12. Must-Have

For all other issues the posting time is respected.

**Comment by apobekiaris** [comment]
>Is there a possibilty to create ModelMapperAssemblyWin.dll in RAM, too?

Nope, the assembly generated from ModelMapper is used to extend the model and cannot be dynamic as per XAF requirement. However once generated it won't be generated again. There are a few tests to it at 

https://github.com/eXpandFramework/DevExpress.XAF/blob/master/src/Tests/ModelMapper/TypeMappingServiceTests/AssemblyTests.cs

if the Mapper assembly is generated while it exists after compilation I consider it a bug, and need details to repro it in order to fix it.

It is also possible to modify the generation path by changing the TypeMappingService `OutputAssembly`  field. The field is internal currently however reflection can be used to change it in accordance to this line

https://github.com/eXpandFramework/DevExpress.XAF/blob/c11eee3796323b9fcfba01bb6f75cc321f7eb60c/src/Modules/ModelMapper/Services/TypeMapping/PublicMembers.cs#L69

if this solves your issue let me know so I can make the OutputAssembly public

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
