### ISSUE TITLE
WorldCreator Module not working on Blazor

### ISSUE THREAD

**Issue by rajkamal0610** [eXpandFramework/eXpand#898]
Hi,

Am working on worldcreator module on windows version. But now i actually need to work on the same with blazor just to view the form created by desktop version 

How to do that

𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
A clear and concise description

𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
02. ❤ Bronze Sponsor
03. ❤ Sponsor
04. ❤ Backer
05. Installation
06. ShowStopper
07. Nuget
08. Contribution
09. BreakingChange
10. ReproSample
11. Deployment
12. Must-Have

For all other issues the posting time is respected.

**Comment by Toastbrotbaby** [comment]
Vielen Dank für Ihre eMail. 
Ich bin vom 21.12.-24.12. nicht im Büro und nur sporadisch per Mail oder Telefon erreichbar. Ihre Mail wird jedoch regelmäßig gelesen und so schnell wie möglich bearbeitet.
Ich wünsche Ihnen eine schöne Weihnachtszeit!
Herzliche Grüße
Thorsten Altmann
opt-it Solutions GmbH
Hi,



Am working on worldcreator module on windows version. But now i actually need to work on the same with blazor just to view the form created by desktop version 





How to do that









𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻

A clear and concise description



𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀

We will try to answer all questions that do not require research within 24hr.

To prioritize cases that require research we use the following labels in order.



01. ❇️ Exclusive-Services

02. ❤ Bronze Sponsor

03. ❤ Sponsor

04. ❤ Backer

05. Installation

06. ShowStopper

07. Nuget

08. Contribution

09. BreakingChange

10. ReproSample

11. Deployment

12. Must-Have



For all other issues the posting time is respected.



-- 

Reply to this email directly or view it on GitHub:

https://github.com/eXpandFramework/eXpand/issues/898

You are receiving this because you are subscribed to this thread.



Message ID: ***@***.***>
To: "eXpandFramework/eXpand" ***@***.***>

Cc: "Subscribed" ***@***.***>

Reply-To: "eXpandFramework/eXpand" ***@***.***>

**Comment by apobekiaris** [comment]
the WebForms package is not ported to Blazor, but the Win supports .net5.

**Comment by Toastbrotbaby** [comment]
Vielen Dank für Ihre eMail. 
Ich bin vom 21.12.-24.12. nicht im Büro und nur sporadisch per Mail oder Telefon erreichbar. Ihre Mail wird jedoch regelmäßig gelesen und so schnell wie möglich bearbeitet.
Ich wünsche Ihnen eine schöne Weihnachtszeit!
Herzliche Grüße
Thorsten Altmann
opt-it Solutions GmbH
the WebForms package is not ported to Blazor, but the Win supports .net5.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/eXpandFramework/eXpand/issues/898#issuecomment-999476166
You are receiving this because you commented.

Message ID: ***@***.***>

To: "eXpandFramework/eXpand" ***@***.***>

Cc: "Toast-Coder" ***@***.***>

    "Comment" ***@***.***>

Reply-To: "eXpandFramework/eXpand" ***@***.***>

**Comment by rajkamal0610** [comment]
> the WebForms package is not ported to Blazor, but the Win supports .net5.

Thanks for reply.

If we really want the feature of web in core/blazor, in nearing future we can get in upcoming version or we ourselves able to migrate source


Any hint!!!!

**Comment by apobekiaris** [comment]
not really if u have questions while you attempt migration let me know

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
