### ISSUE TITLE
Version Converter 4.222.2 trying to call powershell.exe in Linux (Ubuntu 20.04)

### ISSUE THREAD

**Issue by pjcunningham** [eXpandFramework/eXpand#981]
𝗗𝗲𝘀𝗰𝗿𝗶𝗯𝗲 𝘁𝗵𝗲 𝗯𝘂𝗴
Compiling a XAF 22.2.4 project on Linux
```shell
dotnet publish -c Release -p:PublishProfile=FolderProfile
```
results in the following error:
```shell
/home/paul/.nuget/packages/xpand.versionconverter/4.222.2/build/Xpand.VersionConverter.targets(4,9): error : /usr/bin/sh: 2: /tmp/MSBuildTemppaul/tmpf93ba13ebd1b4688bc956d2cdab1c6dd.exec.cmd: powershell.exe: not found [/home/paul/www/test.example.com/Test.Blazor.Server/Test.Blazor.Server.csproj]
/home/paul/.nuget/packages/xpand.versionconverter/4.222.2/build/Xpand.VersionConverter.targets(4,9): error MSB3073: The command "powershell.exe –NonInteractive –ExecutionPolicy Unrestricted –command "& { &'/home/paul/.nuget/packages/xpand.versionconverter/4.222.2/build/\Xpand.VersionConverter.ps1' '/home/paul/www/test.example.com/Test.Blazor.Server/Test.Blazor.Server.csproj' '' '' '' ''  '/home/paul/www/test.example.com/Test.Blazor.Server/bin/Release/net6.0/' } " " exited with code 127. [/home/paul/www/test.example.com/Test.Blazor.Server/Test.Blazor.Server.csproj]
```

𝗧𝗼 𝗥𝗲𝗽𝗿𝗼𝗱𝘂𝗰𝗲
1. Windows: Create a new XAF project using the wizard
2. Windows: Add Xpand nuget packages to project, (Xpand.XAF.Web.All, Xpand.XAF.Core.All)
3. Copy project to Linux and try and compile. 

𝗘𝘅𝗽𝗲𝗰𝘁𝗲𝗱 𝗯𝗲𝗵𝗮𝘃𝗶𝗼𝗿
The project to compile

**Comment by apobekiaris** [comment]
I guess the fastest thing is to edit VersionConverter.ps1 and remove its contents

**Comment by pjcunningham** [comment]
Thanks for getting back.

Except powershell.exe is being referenced in many (if not all) Xpand package `*.targets` files. I deleted all of them using the command below and now my project compiles.

```bash
cd ~/.nuget/packages
find . -path "*xpand*" -name "*.targets" -delete
```
Can they be removed from the sources?

**Comment by apobekiaris** [comment]
what is your suggestion? the build is designed to run on a windows machine

**Comment by apobekiaris** [comment]
unfortunately i do not use or develop on linux thus testing your suggestion is very cost consuming for me. I can however merge any PR that contains a fix and test it that does not interfere with the windows build. So feel free to PR

**Comment by apobekiaris** [comment]
to make it clear we cannot remove the targets they are there for a reason, we can conditionally skip them on Linux hoping for the best.

**Comment by pjcunningham** [comment]
I develop and test XAF Blazor apps on Windows but use Linux for production.

Can you tell me (briefly) what the purpose of the *.targets are for and I can research whether skipping them on Linux (production build only) has any undesirable outcome and possibly find alternative syntax for you.

**Comment by apobekiaris** [comment]
as you can see the [CopySymbols.ps1](https://github.com/eXpandFramework/Reactive.XAF/blob/master/Build/targets/CopySymbols.ps1) currently explicitly copies the pdb files to the bin and fixes microsoft.cognitiveservices.speech c# binding. However please note that  the scirpts are a powerful tool we have to do anything when a project is build. Therefore instead of using native msbuild commands I chose powershell which is easier to debug and develop. So what we looking is somethid like a smart way to run powershell on Linux or skip it. Note that pscore is platform agnostic however I chose the standard version to avoid depdendencies.

Nothing is that simple as it looks there is a history of cases we have to consider but in any case i am open to suggestion and will post my thoughts considerations then

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
